Repository deployKF/deployKF, pull requests merged in 2023-08, with the labels that each got.

#12 feat: allow custom documentation links in dashboard
  generator/default_values.yaml
  generator/templates/manifests/deploykf-core/deploykf-dashboard/values.yaml
Labels: changelog/feature, status/ready-to-merge

#14 fix: set `securityContext.fsGroup` on minio pods
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Deployment.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-buckets.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-policies.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-service-accounts.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/values.yaml
Labels: changelog/fix, status/ready-to-merge

#16 feat: create argocd plugin
  README.md
  argocd-plugin/README.md
  argocd-plugin/apply_apps_of_apps.sh
  argocd-plugin/argocd-install/deploykf-plugin/assets-pvc.yaml
  argocd-plugin/argocd-install/deploykf-plugin/plugin.yaml
  argocd-plugin/argocd-install/deploykf-plugin/repo-server-patch.yaml
  argocd-plugin/argocd-install/kustomization.yaml
  argocd-plugin/example-app-of-apps/app-of-apps.yaml
  argocd-plugin/install_argocd.sh
  argocd-plugin/patch_argocd.sh
  generator/default_values.yaml
  generator/helpers/argocd.tpl
  generator/templates/app-of-apps.yaml
  generator/templates/argocd/deploykf-core/deploykf-auth.yaml
  generator/templates/argocd/deploykf-core/deploykf-dashboard.yaml
  generator/templates/argocd/deploykf-core/deploykf-istio-gateway.yaml
  generator/templates/argocd/deploykf-core/deploykf-profiles-generator.yaml
  generator/templates/argocd/deploykf-dependencies/cert-manager.yaml
  generator/templates/argocd/deploykf-dependencies/istio.yaml
  generator/templates/argocd/deploykf-dependencies/kyverno.yaml
  generator/templates/argocd/deploykf-opt/deploykf-minio.yaml
  generator/templates/argocd/deploykf-opt/deploykf-mysql.yaml
  generator/templates/argocd/kubeflow-dependencies/kubeflow-argo-workflows.yaml
  generator/templates/argocd/kubeflow-tools/katib.yaml
  generator/templates/argocd/kubeflow-tools/notebooks--jupyter-web-app.yaml
  generator/templates/argocd/kubeflow-tools/notebooks--notebook-controller.yaml
  generator/templates/argocd/kubeflow-tools/pipelines.yaml
  generator/templates/argocd/kubeflow-tools/poddefaults-webhook.yaml
  generator/templates/argocd/kubeflow-tools/tensorboards--tensorboard-controller.yaml
  generator/templates/argocd/kubeflow-tools/tensorboards--tensorboards-web-app.yaml
  generator/templates/argocd/kubeflow-tools/training-operator.yaml
  generator/templates/argocd/kubeflow-tools/volumes--volumes-web-app.yaml
Labels: changelog/significant, changelog/feature, status/ready-to-merge

#18 fix: minio-console user permissions (update minio)
  generator/default_values.yaml
Labels: changelog/fix, status/ready-to-merge

#17 feat: allow a single ArgoCD to manage deployKF across multiple clusters
  generator/default_values.yaml
  generator/helpers/check-values--incompatible-configs.tpl
  generator/templates/app-of-apps.yaml
  generator/templates/argocd/deploykf-core/deploykf-auth.yaml
  generator/templates/argocd/deploykf-core/deploykf-dashboard.yaml
  generator/templates/argocd/deploykf-core/deploykf-istio-gateway.yaml
  generator/templates/argocd/deploykf-core/deploykf-profiles-generator.yaml
  generator/templates/argocd/deploykf-dependencies/cert-manager.yaml
  generator/templates/argocd/deploykf-dependencies/istio.yaml
  generator/templates/argocd/deploykf-dependencies/kyverno.yaml
  generator/templates/argocd/deploykf-opt/deploykf-minio.yaml
  generator/templates/argocd/deploykf-opt/deploykf-mysql.yaml
  generator/templates/argocd/kubeflow-dependencies/kubeflow-argo-workflows.yaml
  generator/templates/argocd/kubeflow-tools/katib.yaml
  generator/templates/argocd/kubeflow-tools/notebooks--jupyter-web-app.yaml
  generator/templates/argocd/kubeflow-tools/notebooks--notebook-controller.yaml
  generator/templates/argocd/kubeflow-tools/pipelines.yaml
  generator/templates/argocd/kubeflow-tools/poddefaults-webhook.yaml
  generator/templates/argocd/kubeflow-tools/tensorboards--tensorboard-controller.yaml
  generator/templates/argocd/kubeflow-tools/tensorboards--tensorboards-web-app.yaml
  generator/templates/argocd/kubeflow-tools/training-operator.yaml
  generator/templates/argocd/kubeflow-tools/volumes--volumes-web-app.yaml
  generator/templates/argocd/kustomization.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/generate-profile-resources-clusterpolicy.yaml
  sample-values.yaml
Labels: changelog/feature, status/ready-to-merge

#20 docs: move guides to website
  README.md
Labels: changelog/docs
