Repository deployKF/deployKF, pull requests merged in 2024-02, with the labels that each got.

#91 docs: update example ArgoCD to 2.9.6
  argocd-plugin/argocd-install/kustomization.yaml
Labels: changelog/docs

#92 fix: support kyverno chart changes (but keep kyverno version)
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/deploykf-opt/deploykf-mysql/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/kubeflow-tools/katib/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
Labels: changelog/fix

#93 improve: increase kyverno resource limits and add values
  generator/default_values.yaml
  generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
Labels: changelog/improve

#94 improve: use CRD-level "replace" for kyverno ArgoCD app
  generator/templates/argocd/applications/deploykf-dependencies/kyverno.yaml
  generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
Labels: changelog/improve

#90 fix: annotate cloned imagePullSecrets to be ignored by ArgoCD
  generator/templates/manifests/deploykf-dependencies/kyverno/templates/ClusterPolicy-image-pull-secrets.yaml
Labels: changelog/fix

#95 fix: add background filter to restart trigger policies
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-argo-server-openid-secret.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-minio-openid-secret.yaml
  generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile-tools--kubeflow-pipelines.yaml
  generator/templates/manifests/deploykf-opt/deploykf-minio/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/deploykf-opt/deploykf-mysql/templates/ClusterPolicy--restart-on-secret-updates.yaml
  generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/templates/ClusterPolicy-clone-bucket-secret.yaml
  generator/templates/manifests/kubeflow-tools/katib/resources/clone-mysql-secret-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/katib/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-bucket-secret-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-mysql-secret-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
Labels: changelog/fix

#99 fix: prevent CSRF cookie accumulation on auth expiry
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
  generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz.yaml
Labels: changelog/fix

#100 feat: optional sign-in page to stop background request CSRF accumulation
  generator/default_values.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/ConfigMap-theme.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Deployment.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
  generator/templates/manifests/deploykf-core/deploykf-auth/values.yaml
Labels: changelog/feature

#104 improve: argocd sync script should only wait for app health once
  scripts/sync_argocd_apps.sh
Labels: changelog/improve

#102 improve: stop using kyverno to provision kfp profile resources
  generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile-tools--kubeflow-pipelines.yaml
  generator/templates/manifests/deploykf-core/deploykf-profiles-generator/values.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/kustomization.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/params.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/generate-profile-resources-clusterpolicy.yaml
  generator/templates/manifests/kubeflow-tools/pipelines/resources/profile-resources.yaml
Labels: changelog/improve

#108 improve: support `argocd.appNamePrefix` in argocd sync script
  scripts/sync_argocd_apps.sh
Labels: changelog/improve

#109 fix: argocd sync script only seeing first app in each group
  scripts/sync_argocd_apps.sh
Labels: changelog/fix
